name: Build my React site
on:
  push:
    branches: ['master']

jobs:
  run-npm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install and build webpack
        run: |
          npm install
          echo "Run Build..."
          npm run build
